# Run UT, IT, Sonar scan
name: CI workflows

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - data_ingestion_pipeline/**

permissions:
  contents: read

jobs:
  RunUnitTest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./data_ingestion_pipeline
    steps:
      - name: Check out sources code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'corretto'
          cache: maven
      - name: Run UT
        run: |
          mvn -B test --file pom.xml
